services:
  openresty:
    image: openresty/openresty:bookworm
    container_name: ReTargetOpenResty
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./logs:/usr/local/openresty/nginx/logs
      - /home/ubuntu/frontend_2025_1_RePresent/dist:/www-data
      - ./lua-scripts:/usr/local/openresty/lua-scripts
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - retarget_network

  certbot:
    image: certbot/certbot
    container_name: ReTargetCertbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --standalone --non-interactive --agree-tos --email re-target-service@mail.ru -d re-target.ru --keep-until-expiring
    depends_on:
      - openresty
    networks:
      - retarget_network

networks:
  retarget_network:
    external: true
