services:
  openresty:
    build: .
    image: openresty/openresty:bookworm
    container_name: ReTargetOpenResty
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./logs:/usr/local/openresty/nginx/logs
      - /home/ubuntu/frontend_2025_1_RePresent/dist:/www-data
      - ./lua-scripts:/usr/local/openresty/lua-scripts
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - retarget_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --standalone -w /var/www/certbot --force-renewal --email re-target-service@mail.ru -d re-target.ru -d test.re-target.ru --agree-tos
    network_mode: host

networks:
  retarget_network:
    external: true
