services:
  openresty:
    image: openresty/openresty:bookworm
    container_name: ReTargetOpenResty
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./logs:/usr/local/openresty/nginx/logs
      - /home/ubuntu/frontend_2025_1_RePresent/dist:/www-data
      - ./lua-scripts:/usr/local/openresty/lua-scripts
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - retarget_network

networks:
  retarget_network:
    driver: bridge
    name: retarget_network
